/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Corvette.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Corvette(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Corvette.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
      <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.Body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.Body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.Body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.Body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.Body009.geometry} material={materials.Mayan} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.Body012.geometry} material={materials['Silk.001']} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.Body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.Body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.Body016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.Body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.Body018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.Body019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.Object_21.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.TintedGlass} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.TintedGlass} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Light} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Glass_Red} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Glass_Red} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.RoughGlass} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Light} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.TintedGlass} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_97.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Plate} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Shadow} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.Light} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Light} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_158.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_160.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_166.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_182.geometry} material={materials['Glass.001']} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Rubber} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.TintedGlass} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_207.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_14} />
      <mesh geometry={nodes.Object_209.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.Tire} />
      <mesh geometry={nodes.Object_213.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.material_14} />
      <mesh geometry={nodes.Object_215.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.Tire} />
      <mesh geometry={nodes.Object_195.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.material_14} />
      <mesh geometry={nodes.Object_197.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.Tire} />
      <mesh geometry={nodes.Object_201.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.material_14} />
      <mesh geometry={nodes.Object_203.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.Tire} />
      <mesh geometry={nodes.Object_231.geometry} material={materials.Calipers} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_233.geometry} material={materials.BrakePades} />
      <mesh geometry={nodes.Object_234.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_237.geometry} material={materials.Calipers} />
      <mesh geometry={nodes.Object_238.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_239.geometry} material={materials.BrakePades} />
      <mesh geometry={nodes.Object_240.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_219.geometry} material={materials.Calipers} />
      <mesh geometry={nodes.Object_220.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_221.geometry} material={materials.BrakePades} />
      <mesh geometry={nodes.Object_222.geometry} material={materials.RoughMirror} />
      <mesh geometry={nodes.Object_225.geometry} material={materials.Calipers} />
      <mesh geometry={nodes.Object_226.geometry} material={materials.Border} />
      <mesh geometry={nodes.Object_227.geometry} material={materials.BrakePades} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.RoughMirror} />
    </group>
  )
}

useGLTF.preload('/models/Corvette.glb')
