/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/NewCorvette.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Corvette(props) {
  const { nodes, materials } = useGLTF('models/NewCorvette.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Clignotant_retro} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Dessous} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Disk} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Feux_Glass_Red} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Feux_chrome} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Feux_chrome_text} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Feux_glass} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Feux_stop} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Filet} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Frein} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Grille_HP} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Grille_HP_centre} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Grille_HP_noir} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Grille_coffre} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Grille_moteur} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Interieur_light} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Interior_alu_HP} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Interior_alu_HP_line} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Interior_coffre} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Interior_color} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Interior_couture} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Interior_couture_color} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Interior_display} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Interior_logo_Stingray} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Interior_porte_grille} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Interior_siege} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Interior_speed} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Jante_alu} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Jante_ecrous} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Jante_noir} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Logo_Corvette} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Metal_alu} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Metal_noir} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Miroir} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Motor_durit} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Motor_gris} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Motor_metal} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Motor_text} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Phare} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Phare_LED} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Phare_ch_orange} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Phare_optique} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Phare_orange} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Phare_plastique} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Phare_vitre} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Plastique_noir} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.tires} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Radiator} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Body_plastique_noir} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Vitre} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Vitre_ar} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Vitre_noir} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Carbone} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Clignotant_chr_retro} />
    </group>
  )
}

useGLTF.preload('/models/NewCorvette.glb')
